# Generated by Django 5.2.6 on 2025-10-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='ninjas',
            old_name='dodjo_id',
            new_name='dojo',
        ),
    ]
